# ~/.config/starship.toml

add_newline = true
command_timeout = 1000
format = '''
(238)$os$username$hostname$kubernetes$directory(238)$git_branch$git_status
$character(238)
'''

# Drop ugly default prompt characters
[character]
success_symbol = '[Î»](bold green) '
error_symbol = '[â¯](bold red) '
vimcmd_symbol = '[Î»](bold blue) '

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Windows = ' î˜ª'
Arch = ' ó°£‡'
Ubuntu = ' ïŒ›'
Macos = ' ó°€µ'

# Shows the username
[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Shows the hostname
#[hostname]
#ssh_only = false
#format = 'on [$hostname](bold yellow) '
#disabled = false

# Shows current directory
[directory]
truncation_length = 100
truncate_to_repo = false
home_symbol = "~"
read_only_style = "197"
read_only = " ï€£ "
format = "[$path]($style)[$read_only]($read_only_style) "

# Shows current git branch
[git_branch]
symbol = 'îœ¥ '
format = 'via [$symbol$branch]($style) '
# truncation_length = 4
truncation_symbol = 'â€¦/'
style = 'bold red'

# Shows current git status
# [git_status]
# format = '[$all_status$ahead_behind]($style) '
# style = 'bold red'
# conflicted = 'ğŸ³'
# up_to_date = ''
# untracked = 'ï”© '
# ahead = 'â‡¡${count}'
# diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
# behind = 'â‡£${count}'
# stashed = 'ï£– '
# modified = 'ï„ '
# staged = '[++\($count\)](bold red)'
# renamed = 'è¥ '
# deleted = 'ï€” '

[docker_context]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true
