[settings]
default_action = "block"         # or "allow"
log_violations = true
notify_on_block = true
strict_mode = false              # optional: if true, disables temporary overrides

[[blocks]]
name = "Algorithmic Feeds"
active_by_default = true
whitelist = [
  "instagram.com/direct/inbox",
  "instagram.com/p/*",
  "reddit.com/message/inbox",
  "reddit.com/r/*",
  "reddit.com/search*",
  "reddit.com/user/*",
  "twitter.com/i/timeline",
  "youtube.com/@*",
  "youtube.com/c/*",
  "youtube.com/channel/*",
  "youtube.com/feed/library/*",
  "youtube.com/feed/subscriptions",
  "youtube.com/playlist?list=*",
  "youtube.com/results?search_query=*",
  "youtube.com/user/*",
  "youtube.com/watch?*",
  "linkedin.com/jobs*",
]
blacklist = [
  "facebook.com",
  "instagram.com",
  "reddit.com",
  "tiktok.com",
  "twitter.com/home",
  "youtube.com",
  "linkedin.com",
]

[[blocks]]
name = "Stocks"
active_by_default = true
blacklist = [
  "robinhood.com",
  "tradingview.com",
  "finance.yahoo.com",
]

[[blocks]]
name = "Internet"
active_by_default = false
blacklist = [
  "google.com",
]

[[schedule]]
block = "Algorithmic Feeds"
days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
start = "08:00"
end = "21:10"

[[schedule]]
block = "Stocks"
days = ["Mon", "Fri"]
start = "21:04"
end = "21:05"

[[schedule]]
block = "Internet"
days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
start = "00:00"
end = "23:59"
