[font]
size = 15

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
# opacity = 0.95

[terminal]
osc52 = "CopyPaste"

[window.padding]
# x = 0
# y = 2

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true


[mouse]
bindings = [
{ mouse = "Right", action = "Paste" },
]

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"

# Colors (Blood Moon)

# Default colors
[colors.primary]
background = '#141415'
foreground = '#C6C6C4'

# Normal colors
[colors.normal]
black   = '#10100E'
red     = '#C40233'
green   = '#009F6B'
yellow  = '#FFD700'
blue    = '#0087BD'
magenta = '#9A4EAE'
cyan    = '#20B2AA'
white   = '#C6C6C4'

# Bright colors
[colors.bright]
black   = '#696969'
red     = '#FF2400'
green   = '#03C03C'
yellow  = '#FDFF00'
blue    = '#007FFF'
magenta = '#FF1493'
cyan    = '#00CCCC'
white   = '#FFFAFA'
